apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ccu2pm61b-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap-test-organization-jk/rhtap-qe-go:7433b7dd99fa1cac329e7e188dd097b1b10239dd@sha256:f5e70aeaae0621cd518c3ac13015b9bbc6abbdcb9e2ffc6352770f52c990f694
          name: container-image
